version: '2'

services:
  tomcat:
    image: 'tomcat'
    build:
      context: .
    container_name: tomcat
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-58920-0.cloudclusters.net:18208/linea
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080
    volumes:
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=admin123
    ports:
        - "5434:5432"