version: '2'

services:
  api:
    image: "api"
    build:
      context: .
    container_name: api
    depends_on: 
      - db      
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5434/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports: 
      - 8080:8080
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=admin123
    ports:
        - "5434:5432"